### ISSUE TITLE
union operator

### ISSUE THREAD

**Issue by dinosaure** [hannesm/domain-name#3]
Like I would like this kind of operation:

```ocaml
val union : t -> t -> t
```

With this behavior:

```ocaml
let a = Domain_name.of_string_exn "a.b";;
let b = Domain_name.of_string_exn "b.c";;
Domain_name.(to_string (union a b));;
- : "a.b.c"
```

**Comment by hannesm** [comment]
in #5 I implemented `concat`, which is half way what you need. Is this sufficient for you? If not, I'd be interested where you want to use `union` in your code.

**Comment by dinosaure** [comment]
I think it's enough. I need to go to details, but a `concat` with some others stuffs should be enough in my case. Thanks!
